#+TITLE: Consuming eunit surefire xml reports.
#+FILETAGS: :tooling:

#+OPTIONS: ^:nil num:nil toc:nil date:nil author:nil html-postamble:nil
#+SETUPFILE: "./setupfile.org"
#+INCLUDE: "navbar.html" export html
#+HTML_HEAD: <meta name="description" content="rebar3 erlang eunit surefire report" />

* Introduction

Eunit outputs test results on the command line, there is an eunit plugin to
generate 'surefire' style xml output.  This can be consumed by the 'surefire-reports'
maven/mvn tool to generate HTML which might be a little bit more consumable for
some people.


* Basic configuration:

Edit rebar.config in your projects rebar.config and add the "eunit_opts" option as shown below.

#+BEGIN_SRC erlang
{erl_opts, [debug_info]}.
{deps, []}.

%% add this line
{eunit_opts, [verbose, {report, {eunit_surefire, [{dir, "target/surefire-reports"}]}}]}.

{shell, [
    %% {config, "config/sys.config"},
    {apps, [surefire_demo]}
]}.
#+END_SRC


When you run eunit tests (In this case, with 'rebar3 eunit' command), it should create the target/surefire-reports
directory and create XML files, the exact count depending on your project structure and test structures.

At this point you have completed the 'erlang' side of the test tooling. The next step is to configure the 'maven/java'
tooling.


Create a pom.xml file in the projects root directory.

You should modify the ProjectName, url and version to match your tooling:

#+BEGIN_SRC xml
<project>
	<modelVersion>4.0.0</modelVersion>
	<groupId> 1 </groupId>
	<artifactId>ProjectName</artifactId>
	<version> 1 </version>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	<url>https://your-projects-url.com</url>
	<reporting>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-project-info-reports-plugin</artifactId>
				<version>3.1.2</version>
				<!-- Replace with a suitable version -->
			</plugin>
		</plugins>
	</reporting>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.5.4</version>
				<configuration>
					<testFailureIgnore>true</testFailureIgnore>
					<linkXRef>false</linkXRef>
				</configuration>
			</plugin>
			<!--
                            Convert .xml reports into .html report, but without the CSS or images.
			    equivalent: mvn surefire-report:report-only
			-->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-report-plugin</artifactId>
				<version>3.5.4</version>
				<executions>
					<execution>
						<phase>test</phase>
						<goals>
							<goal>report-only</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>

#+END_SRC


A pom.xml file, or Project Object Model XML, is the configuration file for projects built with Apache Maven.  Even
though we build our project with erlang.

Install maven on your computer, apparently all java is cross platorm and super easy to install .  If you're on a
linux, you should use your package manager because it seems to work for me, on other platforms you may want to
look into what best practices are, I couldnt' tell you.

From within the directory containing pom.xml you should run:

#+BEGIN_SRC bash
 mvn surefire-report:report-only
#+END_SRC

This should generate a more complicated data structure.

#+BEGIN_SRC bash
$ surefire_demo tree target 
target
в”њв”Ђв”Ђ reports
в”‚В В  в”њв”Ђв”Ђ css
в”‚В В  в”‚В В  в”њв”Ђв”Ђ apache-maven-fluido-2.0.0-M9.min.css
в”‚В В  в”‚В В  в”њв”Ђв”Ђ print.css
в”‚В В  в”‚В В  в””в”Ђв”Ђ site.css
в”‚В В  в”њв”Ђв”Ђ fonts
в”‚В В  в”‚В В  в”њв”Ђв”Ђ glyphicons-halflings-regular.eot
в”‚В В  в”‚В В  в”њв”Ђв”Ђ glyphicons-halflings-regular.svg
в”‚В В  в”‚В В  в”њв”Ђв”Ђ glyphicons-halflings-regular.ttf
в”‚В В  в”‚В В  в””в”Ђв”Ђ glyphicons-halflings-regular.woff
в”‚В В  в”њв”Ђв”Ђ images
в”‚В В  в”‚В В  в”њв”Ђв”Ђ accessories-text-editor.png
в”‚В В  в”‚В В  в”њв”Ђв”Ђ add.gif
в”‚В В  в”‚В В  в”њв”Ђв”Ђ apache-maven-project-2.png
в”‚В В  в”‚В В  в”њв”Ђв”Ђ application-certificate.png
в”‚В В  в”‚В В  в”њв”Ђв”Ђ contact-new.png
в”‚В В  в”‚В В  в”њв”Ђв”Ђ document-properties.png
в”‚В В  в”‚В В  в”њв”Ђв”Ђ drive-harddisk.png
в”‚В В  в”‚В В  в”њв”Ђв”Ђ fix.gif
в”‚В В  в”‚В В  в”њв”Ђв”Ђ icon_error_sml.gif
в”‚В В  в”‚В В  в”њв”Ђв”Ђ icon_help_sml.gif
в”‚В В  в”‚В В  в”њв”Ђв”Ђ icon_info_sml.gif
в”‚В В  в”‚В В  в”њв”Ђв”Ђ icon_success_sml.gif
в”‚В В  в”‚В В  в”њв”Ђв”Ђ icon_warning_sml.gif
в”‚В В  в”‚В В  в”њв”Ђв”Ђ image-x-generic.png
в”‚В В  в”‚В В  в”њв”Ђв”Ђ internet-web-browser.png
в”‚В В  в”‚В В  в”њв”Ђв”Ђ logos
в”‚В В  в”‚В В  в”‚В В  в”њв”Ђв”Ђ build-by-maven-black.png
в”‚В В  в”‚В В  в”‚В В  в”њв”Ђв”Ђ build-by-maven-white.png
в”‚В В  в”‚В В  в”‚В В  в””в”Ђв”Ђ maven-feather.png
в”‚В В  в”‚В В  в”њв”Ђв”Ђ network-server.png
в”‚В В  в”‚В В  в”њв”Ђв”Ђ package-x-generic.png
в”‚В В  в”‚В В  в”њв”Ђв”Ђ profiles
в”‚В В  в”‚В В  в”‚В В  в”њв”Ђв”Ђ pre-release.png
в”‚В В  в”‚В В  в”‚В В  в”њв”Ђв”Ђ retired.png
в”‚В В  в”‚В В  в”‚В В  в””в”Ђв”Ђ sandbox.png
в”‚В В  в”‚В В  в”њв”Ђв”Ђ remove.gif
в”‚В В  в”‚В В  в”њв”Ђв”Ђ rss.png
в”‚В В  в”‚В В  в”њв”Ђв”Ђ update.gif
в”‚В В  в”‚В В  в””в”Ђв”Ђ window-new.png
в”‚В В  в”њв”Ђв”Ђ img
в”‚В В  в”‚В В  в”њв”Ђв”Ђ glyphicons-halflings-white.png
в”‚В В  в”‚В В  в””в”Ђв”Ђ glyphicons-halflings.png
в”‚В В  в”њв”Ђв”Ђ js
в”‚В В  в”‚В В  в””в”Ђв”Ђ apache-maven-fluido-2.0.0-M9.min.js
в”‚В В  в””в”Ђв”Ђ surefire.html
в””в”Ђв”Ђ surefire-reports
    в”њв”Ђв”Ђ TEST-file_surefire_demo.app.xml
    в””в”Ђв”Ђ TEST-some_test.xml

10 directories, 40 files
#+END_SRC

The html file to open in the browsers is ./target/reports/index.html .  It requires the data directory structure as
specified above, but the index.html could be renamed into a 'once off' like index-05-10-2025.html if you needed
html records,  If historical raw data is required, you could version the XML files.

* Conclusion

The maven surefire reports tool is a simple way to generate html from eunit reports.


* Resources:

https://www.erlang.org/doc/apps/eunit/chapter.html

https://maven.apache.org/surefire/maven-surefire-report-plugin/project-info.html

