#+TITLE: Growing up tracking and hunting in the Australian bush
#+DATE: [2026-08-13 Thu]
#+AUTHOR: Wade Mealing
#+LAYOUT: post

All of what I have done is legal. I do not hunt native animals, only introduced species. I apologise if anyone finds the following details grotesque, but the damage these animals did was often quite nasty.

* Context and Location

Central Queensland, Australia. I had to get permission from farmers and national parks and wildlife if I was to go on their property. I started this when I was around five years old, doing walk hunting which is just the same thing but for a full day. I think this prepared me as a child to long distance tracking. Knowing what tracks look like, mud and fur on trees, how animals traverse rivers, where to start and stop looking for tracks so that I do not waste time looking at the wrong spots.

I have also done this on properties in the Daintree, in far north Queensland. I found rainforest hunting much harder because finding tracks was a challenge and I had to spend time worrying about crocodiles, snakes, and poisonous trees, being prey myself.

Regularly, almost every time that I found tracks I was able to catch at least one to two animals. My largest take down was about thirteen animals, and I would say less than ten times over the course of five years I came home with nothing. I would hunt almost every other weekend.

I followed the steps taught by my father, who is an Australian bushman who seems to know every tree and animal, and can see and hear animals hiding in the bush that I can only spot after trying to look for ten minutes. My mother is equally as good in the bush, with less hunting and more capability when it comes to the people side of things.

* Equipment and Preparation

I hunted with my brother and father, and sometimes mother. 

Basic equipment:
- Knife
- Arm guard(s)
- Water
- Dried meat
- Backpack
- Matches and lighter
- Tourniquet
- First aid kit (not always)

I did use a modern knife. I do not know if that is cheating or not, but I feel like strangling or bashing an animal to death was a bit cruel. I have hunted with dogs a few times, but you can not bring them on national park land so this limits the success.

I sometimes wore leather guards, made by my mother, on my arms and ensured I had some kind of leather scarf around my neck because cats get scratchy, dogs get bitey, and pigs will try to gore you with tusks. I once used a kickboxer arm guard, but it had holes and I was bitten through the holes, so I am not doing that again.

I did not wear shoes when hunting in Central Queensland. It seemed safe enough and I did not impale myself too often; feet adapt.

I mostly hunted pigs, dogs (not dingoes), large cats, or deer. I have successfully caught deer only less than a handful of times.

* Tactics and Execution

This is the ideal situation. It does not always work this way, but it is the goal, and one needs to adapt to changes as they happen.

** Tracking Phase

Walk an area that has prints, track the prints, and follow the freshest ones. These paths you can use later, because animals will frequently go back to an area they know if you lose them.

Usually the best place to start tracking is around crops and other large animals. Pigs and cats will separate young offspring from the group and kill them for food. By paying attention, you can get a good idea of their behaviour, as animals will repeat successful behaviour that gives them food and water.

This usually, but not always, means that they will be going for water at dusk and dawn. The first step is denying them that water by waiting near the place they get water.

** Golden Rules

- **Golden Rule:** Never unsheath the knife until you are close enough to get the kill. I have had friends come hunting and cut themselves slipping down an embankment with the knife drawn, which is infuriating.
- **Silver Rule:** Drink water. Always have enough fresh water somewhere.
- **Bronze Rule:** If you get lost, do not just start wandering. Relax, do not panic, listen, drink some water, and look for smoke and light.

** The Hunt

You need to be there before they get there, which often means being there well before the sun rises. Stay downwind so that the animal does not smell you and avoid the water.

Ideally you want to be running them east so they are looking into the rising sun. It is not the biggest deal, but if you have this option, take it. The next best option is to have them running on the plain, meaning not in trees, which allows you to track them by sight.

If it is a herd animal, meaning everything on my list except cats, a small group will typically test the area first and the full group will join them when they consider it safe.

At this time it helps to have a second person circle around and take a position about 1000 to 1500 metres out on the return path, again downwind from the tracks, though this can screw up if you have changing winds. Wait until the full group appears, hopefully with enough sun to see prints left behind.

You want enough light to see the tracks, so sometimes this means letting them start to drink before you begin the hunt.

Make yourself seen as the biggest threat possible. Make noise, appear large, and use a torch to make light. Sometimes you can sneak up close enough and get the first kill by hand and then make a lot of noise. This may mean shoulder checking bigger animals, diving on them, or booting them to get them moving.

Chase them towards the person hidden 1000 metres away, being as aggressive as possible in movement to keep them going quickly. This will tire you out, but the second person will continue giving chase. The second must also be as aggressive as possible while trying to keep the main group together.

The animals will usually split, which is very common, but you need to make an educated decision on which animal to pursue. I have had the most luck with males.

You can usually hear the animals and the human making noise and catch up within fifteen to twenty minutes at a moderate pace. We use woops and aahs sounds which travel well and are clear over distance to signify left and right directions if the animals are ahead or moving too quick. I believe this is an older Aboriginal hunting trick in some tribes.

Because the first person is trailing, it is usually a shorter path to catch up. Once caught up, the second can take a breather, have some water, and you keep going.

By this point you are usually at the five to six kilometre mark. Your first animal will either collapse or stop in its tracks for an easy kill. Some smarter animals will attempt to fight you when they realise they are tired.

If you find a log nearby, or if you carry a short walking stick, you can hit it or throw it to spur the animal onwards into further tiredness. You want them to be so tired they can not put up a fight. Pigs will often do this in an attempt to allow the mob to gain extra distance while you deal with it, but ideally you want to keep them moving together.

Large cats will also defend their group this way, usually to buy time to get up a tree or hide, but you must keep on them so they do not have that luxury. It is quite hard to kill a large cat this way because they will try to claw you or get on top of you.

If you are lucky enough to have a third person, position them in high ground nearby so that whatever direction the animals need to go, the travel is downhill, which offers easier movement, better visibility, and adaptability. This should usually be the older person or the newest person, because they have the animals tired and need to continue to present a threat.

** Rotation and Endurance

By this time the animals will be out in new territory and this is where risk happens. They will no longer be following the usual routes they know and can act erratically.

This is where persistence comes in. You need to rotate the front chaser. Have someone with the energy chase the main group, and have the trail people shepherd anyone who breaks free back to the main group. This chase can span anywhere from 10 to 20 kilometres. 

Keep someone at the front continually giving chase. This person should make tracks as clear as possible using footprints in mud and dirt, and leaving arrows in the dirt pointing to the direction they are going, keeping in mind that when tracking humans, foot position is not always the direction they are actually heading.

This is where most injuries happen. Do not ignore them. Rotate the people at the front and leave people behind who are too tired or hurt, telling them to start a small fire, hydrate, and rest. Do not keep going if injured.

If the animal group has any offspring, they usually can not walk by now and the mother will not leave them alone. You need to make a decision on whether to kill the mother and kids now, usually handled by the first and second, while the group continues on.

After a few rotations of slow jogging and tracking, you will find even the most hardened of animals has tried to find cover. Cats go up trees, pigs try to hide in logs and brush, and deer will go to a thicket or grass and crouch. You can usually just meet them where they are, let them try to take the first blow on your armored parts, and then go in for the kill. Most times though they are simply too tired, panting on the ground in a state of fatigue.

Always aim for a one cut kill. Go for the jugular and be sure. It is cruel to have to go for two; sometimes you must, but do not aim for it.

Since the group has split, circle back. The footprints will be very easy to follow now because they will be deeper since they are panicked, fresher, and if there was a sow with piglets, they will be noisy. Usually they will not be resting far from the group. The sun will be around 10 or 11 AM and they will be hot, tired, and thirsty.

If you can not find any, wait downwind for a few hours and see if they come back to the water at dusk. If they have not had any water they will be very thirsty and this chase usually will not go on for more than about 1.5 kilometres.

* Post-Hunt and Reflection

Dragging carcasses back to civilisation can be a real pain in the arse. If you know there are other feral animals in the area, bury it deep or burn it. The fire can also be a good method of finding or giving directions to your hunting mates if you are lost or new.

Most of the pigs had some kind of worms, making them only good after being cooked, and then really only for dogs, so the meat was not that great. The deer meat was passable for jerky, and cats and dogs were not worth the trouble.

I respect marathon runners for even trying. It is very different because you need to plan, think, run, and pace yourself. Hunting is not a sprint; it is a slow, methodical, paced plan. I have many fond memories of spending time with my family in the Australian bush, hunting and camping.
