#+TITLE: Github actions (CI/CD) for LFE.
#+FILETAGS: :tooling:cicd:lfe:
#+OPTIONS: ^:nil num:nil
#+OPTIONS: toc:nil
#+OPTIONS: date:nil
#+OPTIONS: author:nil date:nil
#+OPTIONS: html-postamble:nil

#+OPTIONS: ^:nil num:nil toc:nil date:nil author:nil html-postamble:nil
#+SETUPFILE: "./setupfile.org"
#+INCLUDE: "navbar.html" export html
#+HTML_HEAD: <meta name="description" content="Lisp Flavored Erlang  CI/CD." />

* What is CD/CD ?
:PROPERTIES:
:ID:       0EC050B9-6B4A-42CD-ADE9-98C1371A3377
:PUBDATE:  2026-03-12 Thu 04:23
:END:

If you want to take the headache and room for human error out of delivering software, the current trend is to
use "Continious Integration" and "Continious Delivery" which is a fancy word for automated testing of Merge requests
and automated delivery (whatever that means for your project).

There are many companies in this space, the one that I'm focusing on is githubs CI/CD platform which they have
branded as 'GitHub Actions'.

In their words:

#+BEGIN_EXAMPLE
GitHub Actions is a continuous integration and continuous delivery (CI/CD) platform that
allows you to automate your build, test, and deployment pipeline. You can create workflows
that build and test every pull request to your repository, or deploy merged pull requests
to production.
#+END_EXAMPLE

* Why do I need it ?
:PROPERTIES:
:ID:       67529EC4-5FFE-4967-9414-50F86EA84FB9
:PUBDATE:  2026-03-12 Thu 04:23
:END:

Github have a high level overview of their offerings, along with how they expect it to be
used [[https://resources.github.com/ci-cd/][on their github resources page]]. With minimal effort, you can find many well thought out sites that
extoll the reasoning and logic of using CI/CD, repeating it here would be pointless.

I'm going to talk about it specifically in the context of automating
your LFE testing and container image generation.


Unlike the GitHub docs, I'm not giving you the shiny version, only how I see it.


* How it works.
:PROPERTIES:
:ID:       E826BF61-A72C-46A9-82B7-082491A57BF9
:PUBDATE:  2026-03-12 Thu 04:23
:END:

1. An event occurs on your repository (push, pull, mr ).
2. GitHub searches the .github/workflows directory in your repository for "yml" workflow files that are present.
3. A workflow run is triggered for any workflows that have on: values that match the triggering event.
   Each workflow run will use the version of the workflow that is present in the associated branch at that time.

   (To put it bluntly, it runs with the version that of the '.github/workflow/*.yaml' at the time).


So, how to get this up and running quickly, create a .github/config/ci-cd.yaml file.

Here is an example that I used.

#+BEGIN_SRC yaml.
name: ci/cd

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build and run on OTP-26 and latest LFE.
    runs-on: ubuntu-latest

    container:
      image: erlang:26

    steps:
    - uses: actions/checkout@v4
    - name: Check rebar3 Version
      run: DEBUG=1 rebar3 --version
    - name: Compile
      run: rebar3 lfe compile

    - name: Run Tests
      run: rebar3 as test lfe ltest
#+END_SRC

This spins up a basic ubuntu image, with erlang 26 installed, your specific app may require
another newer (or older) version of the erlang VM (BEAM) please adjust the above as necessary.

Rebar is also installed on the image, and when configured to use lfe, will also fetch the libraries
configured in the rebar.config file during the build process.

This example compiles and runs the tests. 

Listed below is the rebar.config that
worked for me.


#+BEGIN_SRC erlang
{erl_opts, [debug_info]}.

{deps, [
    {lfe, "2.1.2"}
]}.

{plugins, [
    {rebar3_lfe, "0.4.8"}
]}.


{provider_hooks, [
    {pre, [{compile, {lfe, compile}}]}
]}.

{xref_checks,[
    undefined_function_calls,undefined_functions,locals_not_used,
    deprecated_function_calls,deprecated_functions
]}.

{profiles, [
    {prod, [
        {relx, [
            {dev_mode, false},
            {include_erts, true}
       ]}
    ]},
    {test, [
        {deps, [
            {proper, "1.4.0"}
        ]},
        {plugins, [
            {rebar3_proper, "0.12.1"}
        ]},
        {eunit_opts, [verbose]},
        {erl_opts, [{src_dirs, ["src", "test"]}]}
    ]}
]}.

{alias, [
    {coverage, [
        {proper, "-c"},
        {cover, "-v --min_coverage=0"}
    ]},
    {check, [
        compile,
        xref,
        %%dialyzer,
        eunit,
        coverage
    ]}
]}.
#+END_SRC

Now when you do a 'git push' you should see this 'action' being run under the action tab of your project.

This is a very simple GitHub Action, that will allow you to see the basics of how CI/CD works.  The "Delivery"
part of this , I will probably expand on in another post.


* Resources:
:PROPERTIES:
:ID:       196B23BA-5DB0-47EB-863D-EC841F748038
:PUBDATE:  2026-03-12 Thu 04:23
:END:

[[https://github.com/wmealing/CI-CD-TEST/tree/main]]


