#+TITLE: Sending email in common-lisp
#+FILETAGS: :systems:

#+OPTIONS: ^:nil num:nil toc:nil date:nil author:nil html-postamble:nil
#+SETUPFILE: "./setupfile.org"
#+INCLUDE: "navbar.html" export html
#+HTML_HEAD: <meta name="description" content="Sending email from common lisp, (CL)" />

* Summary:
:PROPERTIES:
:ID:       6C5BD6C0-D30F-430C-BB2A-9E28BAA5ED4E
:PUBDATE:  2026-03-12 Thu 04:15
:END:

This page covers how to send an email from your common-lisp coding using the cl-smtp library using googles gmail servers.


* Introduction
:PROPERTIES:
:ID:       A8A06C56-187C-420D-B060-8248071197D0
:PUBDATE:  2026-03-12 Thu 04:15
:END:

This post covers a working example on how to send email from the common-lisp (cl) language using googles servers.  The provided
example has been tested as an individual, and regularly used from the 'google workspace' account.


* Requirements:
:PROPERTIES:
:ID:       F8549E25-A9CD-4F71-873B-F137BCEE32DA
:PUBDATE:  2026-03-12 Thu 04:15
:END:


   An Application password.
   
   [[https://knowledge.workspace.google.com/kb/how-to-create-app-passwords-000009237][Google detailed getting one here.]]  One fact that was missed is that you now need 2FA
   configured for the account or you can not make app passwords.



* The code:
:PROPERTIES:
:ID:       6CE154C2-9555-4EC2-8664-82F7A58E014E
:PUBDATE:  2026-03-12 Thu 04:15
:END:
:LOGBOOK:
- Note taken on [2024-09-13 Fri 00:25]
:END:

   Listed below is the common-lisp code that is required to send email.   The "password" is stored
   in the environment variable GMAIL_KEY, as a single string.  Google often displays on the 'app password'
   page as 4 sets of 4 characters, aka xxxx xxxx xxxx xxxx , however experience shows that there was no space required.

   #+BEGIN_SRC lisp

     (ql:quickload "cl-smtp")
     (ql:quickload "cl-mime")

     (defun email-report (&key to cc subject html)
            "Generic send SMTP mail with some TEXT to RECIEPIENTS"
            (let ((login "youraccount@gmail.com")
                  (passwd (uiop:getenv "GMAIL_KEY")))

              (cl-smtp:with-smtp-mail (out "smtp.gmail.com" to cc
                                           :ssl :tls
                                           :authentication `(,login ,passwd))

                (format out "To: ~A~%" to )
                (format out "Subject: ~A~%" subject)

                (cl-mime:print-mime out (make-instance 'cl-mime:mime
                                                       :type "text" :subtype "html"
                                                       :encoding :base64
                                                       :content html) t t))))

     (devar html-mail-content "<html><h1> THis is html, but not really. </h1></html>")

     (email-report :to "someone@example.com"
                   :cc *cc-list*
                   :subject email-subject
                   :html html-content)
   #+END_SRC

* Ideas for improvement.
:PROPERTIES:
:ID:       EED50708-6AC3-42F9-838E-1E98EED3ED0F
:PUBDATE:  2026-03-12 Thu 04:15
:END:

** 1. Secret Storage mechanism.
:PROPERTIES:
:ID:       559A7E1C-0431-41DB-B171-9179DD0AEC80
:END:

   The application password needs to be stored somewhere, my advice is not to have it stored in plaintext.

   If your application is hosted on a containerized platform, you can pass it as environment variables, or
   some of them have secrets file.

** 2. Preventing secret leaks.
:PROPERTIES:
:ID:       71C6BAF1-1A6F-495D-884E-C3198152A06C
:END:

   After the secret is loaded into memory, destroy the file or environment setting so it is harder for attackers
   to abuse the information.

   #+BEGIN_SRC lisp
  (setf (uiop:getenv "SOME_ENVIRONMENT_VARIABLE") "PASSWORD-REMOVED-FOR-SECURITY-REASONS")
   #+END_SRC

   When it is loaded, use  [[https://github.com/rotatef/secret-values][Secret Values]] which will prevent passwords appearing in backtraces or logs.

** 3. Preventing accidental/intention spamming.
:PROPERTIES:
:ID:       0C2C61F4-B787-403A-99C6-0754D176328A
:END:

   Your application may accidentally send out hundreds of mail if a function is run repeatedly accidentally.
   It is important that the program keep an accurate, reliable mechanism to know when a limits are abused.

* Conclusion
:PROPERTIES:
:ID:       247215DA-3640-45D7-AF93-C5B56C1F7A8F
:PUBDATE:  2026-03-12 Thu 04:15
:END:



* Resources:
:PROPERTIES:
:ID:       4CBEA1D4-3747-44C4-9E93-005E8C383EB3
:PUBDATE:  2026-03-12 Thu 04:15
:END:

https://gitlab.common-lisp.net/cl-smtp/cl-smtp
