#+TITLE: Toshiba Toughpad FZ-G1 mk3
#+FILETAGS: :security:
#+OPTIONS: ^:nil num:nil toc:nil
#+SETUPFILE: "./setupfile.org"
#+INCLUDE: "navbar.html" export html
#+HTML_HEAD: <meta name="description" content="Toshiba Toughpad FZ-G1 mk3" />


I've got *Fedora 32* installed on this system. The advice below may work on other distributions. I'd be happy to do more of these if anyone wanted to throw a few Toughpads my way.

* Brightness:
:PROPERTIES:
:ID:       7109DEEC-1481-4924-8A72-18638CD64025
:PUBDATE:  2026-03-12 Thu 04:14
:END:

The brightness controls in *Gnome 3 / Fedora 32* do not work out of the box. These instructions have also been tested on *Red Hat Enterprise Linux 8*.

You need to create file =/usr/share/X11/xorg.conf.d/20-intel.conf= and place this in the file:

#+BEGIN_SRC shell
Section "Device"
            Identifier  "card0"
            Driver      "intel"
            Option      "Backlight"  "intel_backlight"
            BusID       "PCI:0:2:0"
EndSection
#+END_SRC

This will create an additional backlight directory in =/sys/class/backlight=. At this point you might find there are two possible backlights, *'panasonic'* and *'intel_backlight'*.

The next step was to *blacklist the 'panasonic_laptop' kernel module*. This ensured that the Gnome 3 brightness/contrast functionality would find *ONLY* the =intel_backlight= backlight controls and work correctly.

I achieved this by creating a file in =/etc/modprobe.d/panasonic-backlist.conf=:

#+BEGIN_SRC shell
blacklist panasonic_laptop
#+END_SRC

If you want these changes to take effect immediately run the command:

#+BEGIN_SRC shell
rmmod panasonic_laptop
#+END_SRC

And restart the X session by logging in and out.

There should only be a single directory in =/sys/class/backlight= and the Gnome brightness controls should work correctly.

* DOCK PINOUT
:PROPERTIES:
:ID:       1D34FF0B-40D8-4502-B9C9-D05914671368
:PUBDATE:  2026-03-12 Thu 04:14
:END:

I'm interested in building a dock for this laptop. There are a lot of docks available for it, some as expensive as 1.5k, which are well beyond the acceptable price range that I'm willing to pay for a dock.

I'm going to do some research on the system's pins, and then find out what I can build that will be a suitable dock.

#+CAPTION: Unconfirmed Dock Pinout
| PIN | Signal  | Description         |
|-----+---------+---------------------|
|  01 | Shield  |                     |
|  02 |         |                     |
|  03 |         |                     |
|  04 | GRND    |                     |
|  05 | 16V     | Supply (for dock ?) |
|  06 | 16V     |                     |
|  07 | 16V     |                     |
|  08 | 5V      | Supply for usb ?    |
|  09 | 5V      |                     |
|  10 | 5V      |                     |
|  11 | GRND    |                     |
|  12 | D-      | USB D-              |
|  13 | D+      | USB D+              |
|  14 | GRND    |                     |
|  15 | TX+     | ETHERNET TX+        |
|  16 | TX-     | ETHERNET TX-        |
|  17 | GRND    |                     |
|  18 | RX +    | ETHERNET RX+        |
|  19 | RX-     | ETHERNET RX-        |
|  20 | GRND    |                     |
|  21 |         |                     |
|  22 | SHORT ? |                     |
|  23 |         |                     |
|  24 |         |                     |

All of these are unconfirmed, please leave me a note if you can confirm any of these.

From what I read the *MK1 to MK3* have the same pinout.

I have to assume that the system can also be charged through the dock, I just don't know what pins.

* Front facing buttons.
:PROPERTIES:
:ID:       D2D2549D-9777-4B96-A56F-384EC3041728
:PUBDATE:  2026-03-12 Thu 04:14
:END:

The front facing buttons on the Toughpad mostly worked out of the box. I had done some initial setup (implied).

** A1 and A2
:PROPERTIES:
:ID:       06F6FF4C-E83F-45AF-9BAC-8AC0B247F6D2
:END:

Currently have only *A1 working*, *A2 is not working*. I've started [[./toughpad-fz-g1-buttons-acpi.md][chronicaling my investigation]].

** Volume up and volume down
:PROPERTIES:
:ID:       8B7CDF83-AFFD-4CCB-BCC3-B618E3A78A7B
:END:

Status: *working*

** Windows key
:PROPERTIES:
:ID:       A86B829B-7831-479E-972C-722AA2027597
:END:

Status: *working* (Looks like it's working... not sure what it sends)

** Rotate key
:PROPERTIES:
:ID:       0F933DF8-E9FE-46F8-9D0F-074DA6C29231
:END:

Status: *working* (Screen doesn't rotate, not sure what it sends)

** Power button
:PROPERTIES:
:ID:       64027B8A-A1C6-416D-9BB3-15A5D496C337
:END:

Status: *working* (This can power off system)
